version: '3.8'

services:
  db:
    container_name: autospace_db
    image: postgres # using dockerHub. If u have custom image, create with Dockerfile and we can specify as "build: ./frontend"
    restart: always
    ports:
      - 2010:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data_autospace:/var/lib/postgresql/data
volumes:
  db_data_autospace:
